apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: 
        image: nginx
        ports: 
        - containerPort: 80